### ISSUE TITLE
mock/create: não está publicando dns

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer-app#241]
criei um mock na parte da tarde e ele não publicou o dns (imagem continua vermelha), porem o host está respondendo.

<img width="520" alt="Screenshot 2024-03-14 at 21 41 49" src="https://github.com/moclojer/moclojer-app/assets/31996/373a9b11-3909-42f8-9b1a-ec1899116d6b">

endpoint não respospondo: https://lerolero-avelino.moclojer.com/hello/avelino
<img width="523" alt="Screenshot 2024-03-14 at 21 43 45" src="https://github.com/moclojer/moclojer-app/assets/31996/6ae3d84d-c7b9-4ae8-ba49-6593a92748b5">

```yaml
# The following schema is an example of how you can
# use the power of Moclojer to create your applications.
#
# Documentation: https://docs.moclojer.com
# Source Code: https://github.com/moclojer/moclojer

# This mock register route: GET /hello/:username
- endpoint:
    # Note: the method could be omitted because GET is the default
    method: GET
    path: /hello/:username
    response:
      # Note: the status could be omitted because 200 is the default
      status: 200
      headers:
        Content-Type: application/json
      # Note: the body will receive the value passed in the url using the
      # :username placeholder
      body: |
        {
          "hello": "{{path-params.username}}!"
        }
```
