### ISSUE TITLE
yaml linter: validar estrutura do webhook

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer-app#267]
hoje não estamos validando a estrutura de `webhook`

```yaml
    webhook:
      sleep-time: 60
      if: path-params.project-name = "moclojer"
      url: https://moclojer.com/api/webhook
      method: GET
      body: >
        {"project-name": "{{path-params.project-name}}"}
```
[doc/referencia](https://docs.moclojer.com/webhook-support)

https://github.com/moclojer/moclojer-app/blob/7a5b64ea41f2456a48920d7bef3f6c3a1869a518/src/front/app/dashboard/linter.cljs#L20-L24
