### ISSUE TITLE
`:webhook :if` é "opcional"

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer-app#275]
![Screenshot 2024-04-18 at 17 06 42](https://github.com/moclojer/moclojer-app/assets/31996/261358c2-8659-4d17-9a91-267a9af04822)

> if (field is optional, default value of true) [...] [ref](https://docs.moclojer.com/webhook-support)

```yaml
- endpoint:
    method: POST
    path: /supabase-auth
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {"reciver": true}
    webhook:
      sleep-time: 0
      url: https://discord.com/api/webhooks/1225389817374965802/k6sSfK4RAkh8aXOuHt1ssj1U-HqdMBSCfBUsSu1OCV-GJG7nifc-_0L1jEgzMyRgsOBp
      method: POST
      headers:
        Content-Type: application/json
      body: >
        {"username": "SupaAuth", "content": "New user created, we are growing!"}
- endpoint:
    method: POST
    path: /github/:repo
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {"reciver": true}
    webhook:
      sleep-time: 0
      url: https://discord.com/api/webhooks/1230521862652428332/mN9qmYwwGFGN5BAsc2E3MofbMH2fnYRGcVcPHMH-utB5c05Yp4yLp0f0fW-JVqStSLbJ
      method: POST
      headers:
        Content-Type: application/json
      body: >
        {"username": "GitHub", "content": "commit/author: {{json-params.head_commit.author.name}} | [commit/message]({{json-params.head_commit.url}}): {{json-params.head_commit.message}}"}
```
